//
// Redmine CLI
// Copyright © 2020 Alexey Korolev <alphatroya@gmail.com>
//

#if !canImport(ObjectiveC)
    import XCTest

    extension GherkinHighlighterTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__GherkinHighlighterTests = [
            ("testShouldSuccessfullyHighlightItems", testShouldSuccessfullyHighlightItems),
        ]
    }

    public func __allTests() -> [XCTestCaseEntry] {
        [
            testCase(GherkinHighlighterTests.__allTests__GherkinHighlighterTests),
        ]
    }
#endif
