name: Swift

on: [push]

jobs:
  test:
    runs-on: macos-11

    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 12.5.1

    - uses: actions/checkout@v1

    - name: Launch tests
      run: |
        swift test
